---

- src: https://github.com/Shurroo/zsh.git
  name: Shurroo.zsh

- src: https://github.com/Shurroo/git.git
  name: Shurroo.git

- src: https://github.com/Shurroo/oh-my-zsh-p10k.git
  name: Shurroo.oh-my-zsh-p10k

- src: https://github.com/Shurroo/iterm2.git
  name: Shurroo.iterm2

- src: https://github.com/Shurroo/homebrew.git
  name: Shurroo.homebrew

...
